name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Access MARVEL_PUBLIC
      env:
        MARVEL_PUBLIC: ${{ secrets.MARVEL_PUBLIC }}
      run: echo MARVEL_PUBLIC=\"MARVEL_PUBLIC\" > ./local.properties
    - name: Access MARVEL_PRIVATE
      env:
        MARVEL_PRIVATE: ${{ secrets.MARVEL_PRIVATE }}
      run: echo MARVEL_PRIVATE=\"MARVEL_PRIVATE\" > ./local.properties
    - name: Read local.properties
      id: local
      uses: juliangruber/read-file-action@v1
      with:
        path: ./local.properties
        - name: Echo local.properties
          run: echo ${{ steps.package.outputs.content }}
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
